pub mod adapters;
mod action_context;
mod agent_pane;
pub mod app;
mod appmon;
pub mod boot;
pub mod boot_order;
mod capture;
mod commands;
pub mod config;
mod console;
pub mod console_eval;
pub mod context_menu;
pub mod coordinator;
pub mod image_handler;
mod input;
mod inspector;
pub mod jobs;
#[allow(dead_code)]
mod keystroke_fx;
pub mod logging;
mod mouse;
pub mod notifications;
mod pane;
pub mod profiler;
mod render;
mod render_overlay;
pub mod resources;
pub mod runtime;
mod selftest;
pub mod session;
pub mod settings;
pub(crate) mod settings_ui;
pub mod supervisor_client;
mod sysmon;
mod update;
mod video;
