//! The [`LoopSource`] trait and its supporting types.
//!
//! A `LoopSource` is the *input side* of a [`crate::runner::LoopRunner`]:
//! it produces one [`LoopInput`] per iteration, signals "no work right now"
//! via [`LoopPullResult::Empty`], or terminates the loop with
//! [`LoopPullResult::Done`] or [`LoopPullResult::Error`].
//!
//! Concrete implementations live under [`crate::sources`].
//!
//! # Why this is sync, not async
//!
//! `LoopSource::next` runs once per FSM tick on the runner's tokio task and
//! must remain non-blocking. For MVP the supported sources ([`crate::sources::CronSource`],
//! [`crate::sources::LoopMessageQueueSource`]) consult in-process state only —
//! a system-clock read and a mutex pop. Future GitHub-backed sources from
//! C3 will own a tokio task internally and present the same sync `next`
//! surface; sync at the trait boundary keeps the runner FSM linear.

use serde::{Deserialize, Serialize};

/// Per-pull context handed to a [`LoopSource`].
///
/// Carries identification fields the source may want to use for logging,
/// correlation, or rate-limit gating. Deliberately minimal — anything the
/// source needs persistently belongs as a field on the source itself, not
/// in this context struct.
#[derive(Debug, Clone)]
pub struct LoopContext {
    /// The user-chosen `id` from the [`crate::LoopSpec`] driving this runner.
    /// Sources use it to tag emitted messages (so consumers can trace
    /// causality) and to scope log lines.
    pub loop_id: String,
}

/// Outcome of one [`LoopSource::next`] call.
///
/// The runner FSM in [`crate::runner::LoopRunner`] interprets each variant:
///
/// - [`LoopPullResult::Available`] — transition to `Dispatching` with the
///   carried input.
/// - [`LoopPullResult::Empty`] — sleep for the runner's idle backoff and
///   re-poll. Used by sources that legitimately have no work right now
///   (an empty queue, a cron tick that hasn't elapsed yet).
/// - [`LoopPullResult::Done`] — terminal. Runner transitions to `Stopped`
///   with a "source exhausted" reason.
/// - [`LoopPullResult::Error`] — terminal. Runner transitions to `Stopped`
///   with the error string embedded in the reason.
#[derive(Debug)]
pub enum LoopPullResult {
    /// A new input is ready for dispatch.
    Available(LoopInput),
    /// The source has no work *right now*; the runner should back off and
    /// re-poll. Distinct from [`Self::Done`] in that the source expects to
    /// have work again in the future.
    Empty,
    /// The source is permanently exhausted. Terminal — the runner stops.
    Done,
    /// Pulling the source failed in a way that should terminate the loop
    /// (network error, gh-CLI missing, etc.). The runner records the
    /// message as the stop reason.
    Error(LoopSourceError),
}

/// One unit of work produced by a [`LoopSource`].
///
/// `key` is the dedup / log handle (e.g. `"issue#1241"`); `payload` is the
/// raw JSON the runner forwards to the agent's system prompt and the
/// effect runner. `correlation_id` is the cross-system trace handle the
/// runner emits with every state transition.
#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct LoopInput {
    /// Stable, source-meaningful key — useful for deduplication, logging,
    /// and the runner's `current_input.key` field for diagnostics.
    pub key: String,
    /// Free-form JSON payload. Whatever the agent or effect runner needs.
    pub payload: serde_json::Value,
    /// Cross-system correlation id, generated by the source (queue sources
    /// reuse the producing loop's id; cron sources mint a fresh one).
    pub correlation_id: CorrelationId,
}

/// Newtype wrapping a correlation identifier string.
///
/// The runner uses this to thread one stable id through a single loop
/// iteration — source → dispatch → result → effects — so observability
/// systems can join events across the spawned agent and the runner FSM.
///
/// Kept as `String` rather than `Uuid` for two reasons: (a) queue sources
/// inherit ids from the producing loop's message header, which is a free
/// string; (b) tests want to assert exact correlation values and `Uuid::v4`
/// would force `Eq` matching against a regex.
#[derive(Debug, Clone, PartialEq, Eq, Hash, Deserialize, Serialize)]
pub struct CorrelationId(pub String);

impl CorrelationId {
    /// Build a correlation id from any string-like value.
    #[must_use]
    pub fn new(s: impl Into<String>) -> Self {
        Self(s.into())
    }

    /// Borrow the inner string.
    #[must_use]
    pub fn as_str(&self) -> &str {
        &self.0
    }
}

impl std::fmt::Display for CorrelationId {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(&self.0)
    }
}

/// Errors a [`LoopSource`] can surface from `next`.
///
/// Coarse on purpose — the runner only branches on "terminal vs. retryable",
/// and right now everything in this enum is terminal. Future sources may
/// extend the variant list (rate-limited, transient-network, etc.) at which
/// point we'll add a `retryable()` accessor to the trait.
#[derive(Debug, thiserror::Error)]
pub enum LoopSourceError {
    /// An external dependency (e.g. the `gh` CLI) is missing or unusable.
    #[error("source dependency unavailable: {0}")]
    DependencyUnavailable(String),

    /// The source's underlying transport failed.
    #[error("source transport error: {0}")]
    Transport(String),

    /// The source's configuration is inconsistent (e.g. a `Queue` source
    /// pointing at a never-published queue name).
    #[error("source misconfiguration: {0}")]
    Misconfigured(String),
}

/// Abstraction over "where does this loop's work come from".
///
/// Implementations are owned by a single [`crate::runner::LoopRunner`] and
/// called once per FSM tick. `next` is sync and must return promptly — see
/// the module-level note on the sync/async boundary.
pub trait LoopSource: Send + Sync {
    /// Pull the next available input, or signal that the source is empty,
    /// done, or errored.
    fn next(&mut self, ctx: &LoopContext) -> LoopPullResult;
}

#[cfg(test)]
mod tests {
    use super::*;
    use serde_json::json;

    #[test]
    fn correlation_id_display_matches_inner_string() {
        let id = CorrelationId::new("loop-42:tick-7");
        assert_eq!(id.to_string(), "loop-42:tick-7");
        assert_eq!(id.as_str(), "loop-42:tick-7");
    }

    #[test]
    fn loop_input_roundtrips_through_json() {
        let input = LoopInput {
            key: "issue#1".to_string(),
            payload: json!({"x": 1}),
            correlation_id: CorrelationId::new("c1"),
        };
        let s = serde_json::to_string(&input).expect("serialize");
        let back: LoopInput = serde_json::from_str(&s).expect("deserialize");
        assert_eq!(back.key, "issue#1");
        assert_eq!(back.payload, json!({"x": 1}));
        assert_eq!(back.correlation_id, CorrelationId::new("c1"));
    }

    /// Verify the trait is object-safe — the runner stores it as
    /// `Box<dyn LoopSource>`.
    #[test]
    fn loop_source_is_object_safe() {
        struct AlwaysEmpty;
        impl LoopSource for AlwaysEmpty {
            fn next(&mut self, _ctx: &LoopContext) -> LoopPullResult {
                LoopPullResult::Empty
            }
        }
        let mut boxed: Box<dyn LoopSource> = Box::new(AlwaysEmpty);
        let ctx = LoopContext { loop_id: "t".to_string() };
        match boxed.next(&ctx) {
            LoopPullResult::Empty => {}
            other => panic!("expected Empty, got {other:?}"),
        }
    }
}
