//! Goal-directed autonomy — the brain decides what to work on.
//!
//! Two systems working together:
//! - **GoalPursuit** (BabyAGI pattern): persistent task queue, LLM-driven
//!   task creation and prioritization, execute → generate new tasks → loop.
//! - **ReflexionMemory** (Reflexion pattern): when a task fails, generate
//!   a verbal reflection and store it. On retry, inject prior reflections
//!   into the prompt. The brain learns from its own mistakes without
//!   fine-tuning.
//!
//! References:
//! - Nakajima, "BabyAGI" (2023) — task queue + creation + prioritization loop
//! - Shinn et al., "Reflexion" (NeurIPS 2023) — verbal reinforcement learning

use serde::{Deserialize, Serialize};
use std::collections::VecDeque;

// ---------------------------------------------------------------------------
// Task queue (BabyAGI pattern)
// ---------------------------------------------------------------------------

/// Unique monotonic task identifier.
pub type TaskId = u64;

/// A single goal-directed task in the brain's queue.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct BrainTask {
    pub id: TaskId,
    pub name: String,
    pub origin: TaskOrigin,
    pub result: Option<TaskResult>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum TaskOrigin {
    /// Seeded by user (console command, agent request).
    User,
    /// Generated by the brain after completing another task.
    Derived { parent_id: TaskId },
    /// Created by the proactive scanner.
    Proactive,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TaskResult {
    pub data: String,
    pub success: bool,
    pub timestamp_secs: u64,
}

/// The brain's task queue. FIFO with full-replacement on reprioritize.
pub struct TaskQueue {
    tasks: VecDeque<BrainTask>,
    next_id: TaskId,
}

impl TaskQueue {
    pub fn new() -> Self {
        Self {
            tasks: VecDeque::new(),
            next_id: 1,
        }
    }

    pub fn push(&mut self, name: String, origin: TaskOrigin) -> TaskId {
        let id = self.next_id;
        self.next_id += 1;
        self.tasks.push_back(BrainTask {
            id,
            name,
            origin,
            result: None,
        });
        id
    }

    pub fn pop_front(&mut self) -> Option<BrainTask> {
        self.tasks.pop_front()
    }

    pub fn is_empty(&self) -> bool {
        self.tasks.is_empty()
    }

    pub fn len(&self) -> usize {
        self.tasks.len()
    }

    /// Replace the entire queue (after LLM prioritization).
    pub fn replace(&mut self, tasks: Vec<BrainTask>) {
        self.tasks = VecDeque::from(tasks);
    }

    pub fn task_names(&self) -> Vec<&str> {
        self.tasks.iter().map(|t| t.name.as_str()).collect()
    }
}

// ---------------------------------------------------------------------------
// Goal pursuit (BabyAGI execution loop)
// ---------------------------------------------------------------------------

/// Goal-directed execution mode for the brain.
///
/// Maintains a task queue alongside the existing event-driven scoring.
/// When active, the brain pops tasks, executes them, generates new tasks
/// from results, and reprioritizes the queue.
pub struct GoalPursuit {
    pub objective: Option<String>,
    pub queue: TaskQueue,
    pub completed: Vec<(BrainTask, TaskResult)>,
    pub max_cycles: u32,
    pub current_cycle: u32,
}

impl GoalPursuit {
    pub fn new() -> Self {
        Self {
            objective: None,
            queue: TaskQueue::new(),
            completed: Vec::new(),
            max_cycles: 20,
            current_cycle: 0,
        }
    }

    /// Activate goal pursuit with a user-provided objective.
    pub fn set_objective(&mut self, objective: String, initial_task: String) {
        self.objective = Some(objective);
        self.queue = TaskQueue::new();
        self.queue.push(initial_task, TaskOrigin::User);
        self.completed.clear();
        self.current_cycle = 0;
    }

    /// Returns true if the brain should run a goal-directed cycle.
    pub fn is_active(&self) -> bool {
        self.objective.is_some() && !self.queue.is_empty()
    }

    pub fn should_stop(&self) -> bool {
        self.queue.is_empty() || self.current_cycle >= self.max_cycles
    }

    /// Build the execution prompt (BabyAGI's execution_agent).
    pub fn build_execution_prompt(&self, task: &BrainTask) -> String {
        let objective = self.objective.as_deref().unwrap_or("(none)");

        // Context: last 5 completed tasks (recency-based).
        let context: String = self
            .completed
            .iter()
            .rev()
            .take(5)
            .map(|(t, r)| format!("- {}: {}", t.name, r.data))
            .collect::<Vec<_>>()
            .join("\n");

        let mut prompt = format!(
            "You are Phantom, an AI brain in a terminal emulator. \
             Perform one task for this objective: {objective}\n"
        );
        if !context.is_empty() {
            prompt.push_str(&format!(
                "Previously completed tasks:\n{context}\n"
            ));
        }
        prompt.push_str(&format!("\nYour task: {}\n", task.name));
        prompt
    }

    /// Record a completed task and its result.
    pub fn record_completion(&mut self, task: BrainTask, result: TaskResult) {
        self.completed.push((task, result));
        self.current_cycle += 1;
    }

    /// Get a summary of completed work for display.
    pub fn summary(&self) -> String {
        let obj = self.objective.as_deref().unwrap_or("(none)");
        let done = self.completed.len();
        let remaining = self.queue.len();
        let successes = self.completed.iter().filter(|(_, r)| r.success).count();
        format!(
            "Goal: {obj} | {done} done ({successes} ok) | {remaining} remaining | cycle {}/{}",
            self.current_cycle, self.max_cycles
        )
    }
}

// ---------------------------------------------------------------------------
// Task creation + prioritization prompts (BabyAGI)
// ---------------------------------------------------------------------------

/// Build the task-creation prompt for the LLM.
pub fn build_task_creation_prompt(
    objective: &str,
    completed_task: &str,
    result: &str,
    incomplete_tasks: &[&str],
) -> String {
    let mut prompt = format!(
        "You are an AI brain in a terminal emulator called Phantom.\n\
         Use the result from a completed task to create new tasks for this objective: {objective}\n\n\
         Completed task: {completed_task}\nResult:\n{result}\n"
    );
    if !incomplete_tasks.is_empty() {
        let list = incomplete_tasks.join(", ");
        prompt.push_str(&format!("Incomplete tasks: {list}\n\
             New tasks must not overlap with incomplete tasks.\n"));
    }
    prompt.push_str(
        "Return new tasks as a numbered list (one per line). \
         If no new tasks needed, write \"No new tasks.\"\n"
    );
    prompt
}

/// Build the prioritization prompt for the LLM.
pub fn build_prioritization_prompt(objective: &str, task_names: &[&str]) -> String {
    let list = task_names.iter().map(|t| format!("- {t}")).collect::<Vec<_>>().join("\n");
    format!(
        "Prioritize these tasks for the objective: {objective}\n\n\
         Tasks:\n{list}\n\n\
         Sort from highest to lowest priority. Higher-priority tasks are \
         prerequisites or more essential.\n\
         Do not remove any. Return as a numbered list.\n"
    )
}

/// Parse a numbered-list LLM response into task names.
pub fn parse_task_list(response: &str) -> Vec<String> {
    let mut tasks = Vec::new();
    for line in response.lines() {
        let trimmed = line.trim();
        let Some((num_part, name_part)) = trimmed.split_once('.') else { continue };
        let has_digit = num_part.chars().any(|c| c.is_ascii_digit());
        if !has_digit { continue; }
        let name: String = name_part.trim().to_string();
        if !name.is_empty() && !name.to_lowercase().starts_with("no new task") {
            tasks.push(name);
        }
    }
    tasks
}

// ---------------------------------------------------------------------------
// Reflexion memory (verbal reinforcement learning)
// ---------------------------------------------------------------------------

/// Maximum reflections kept per task (sliding window from the paper).
const MAX_REFLECTIONS: usize = 3;

/// A single reflection — what went wrong and the plan for next time.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Reflection {
    pub trial: u32,
    pub text: String,
    pub created_at: u64,
}

/// Episodic memory for a specific task type.
///
/// Stored in MemoryStore under key `reflexion:{task_signature}`.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ReflexionMemory {
    pub task_signature: String,
    pub objective: String,
    pub reflections: Vec<Reflection>,
    pub trials: u32,
    pub solved: bool,
}

impl ReflexionMemory {
    pub fn new(task_signature: String, objective: String) -> Self {
        Self {
            task_signature,
            objective,
            reflections: Vec::new(),
            trials: 0,
            solved: false,
        }
    }

    /// Add a reflection from a failed trial. Maintains sliding window.
    pub fn add_reflection(&mut self, text: String) {
        let now = std::time::SystemTime::now()
            .duration_since(std::time::UNIX_EPOCH)
            .map(|d| d.as_secs())
            .unwrap_or(0);

        self.reflections.push(Reflection {
            trial: self.trials,
            text,
            created_at: now,
        });
        self.trials += 1;

        // Paper: truncate to last 3 reflections.
        if self.reflections.len() > MAX_REFLECTIONS {
            let drain = self.reflections.len() - MAX_REFLECTIONS;
            self.reflections.drain(..drain);
        }
    }

    pub fn get_reflection_texts(&self) -> Vec<&str> {
        self.reflections.iter().map(|r| r.text.as_str()).collect()
    }

    pub fn mark_solved(&mut self) {
        self.solved = true;
    }
}

/// Build the self-reflection prompt (Reflexion paper, exact pattern).
pub fn build_reflection_prompt(
    failed_trajectory: &str,
    prior_reflections: &[&str],
) -> String {
    let mut prompt = String::from(
        "You will be given the history of a failed task attempt in a terminal environment. \
         Do not summarize the environment. Think about the strategy and path you took. \
         Devise a concise new plan that accounts for your mistake, referencing specific \
         actions you should have taken.\n\n\
         Failed attempt:\n"
    );
    prompt.push_str(failed_trajectory);

    if !prior_reflections.is_empty() {
        prompt.push_str("\n\nPlans from past attempts:\n");
        for (i, r) in prior_reflections.iter().enumerate() {
            prompt.push_str(&format!("Trial #{i}: {}\n", r.trim()));
        }
    }
    prompt.push_str("\nNew plan:");
    prompt
}

/// Inject reflections into an execution prompt.
pub fn inject_reflections(
    base_prompt: &str,
    task_info: &str,
    memory: &ReflexionMemory,
) -> String {
    let mut prompt = base_prompt.to_string();
    let reflections = memory.get_reflection_texts();
    if !reflections.is_empty() {
        prompt.push_str("\n\nLessons from past attempts:");
        for (i, r) in reflections.iter().enumerate() {
            prompt.push_str(&format!("\nTrial {i}: {}", r.trim()));
        }
    }
    prompt.push_str(&format!("\nTask: {task_info}"));
    prompt
}

/// Persist a ReflexionMemory to the project MemoryStore.
pub fn save_reflexion(
    store: &mut phantom_memory::MemoryStore,
    mem: &ReflexionMemory,
) -> anyhow::Result<()> {
    let key = format!("reflexion:{}", mem.task_signature);
    let value = serde_json::to_string(mem)?;
    store.set(
        &key,
        &value,
        phantom_memory::MemoryCategory::Context,
        phantom_memory::MemorySource::Auto,
    )?;
    Ok(())
}

/// Load a ReflexionMemory from the project MemoryStore.
pub fn load_reflexion(
    store: &phantom_memory::MemoryStore,
    task_signature: &str,
) -> Option<ReflexionMemory> {
    let key = format!("reflexion:{task_signature}");
    let entry = store.get(&key)?;
    serde_json::from_str(&entry.value).ok()
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn task_queue_push_pop() {
        let mut q = TaskQueue::new();
        let id1 = q.push("first".into(), TaskOrigin::User);
        let id2 = q.push("second".into(), TaskOrigin::User);
        assert_ne!(id1, id2);
        assert_eq!(q.len(), 2);

        let t = q.pop_front().unwrap();
        assert_eq!(t.name, "first");
        assert_eq!(q.len(), 1);
    }

    #[test]
    fn task_queue_replace() {
        let mut q = TaskQueue::new();
        q.push("a".into(), TaskOrigin::User);
        q.push("b".into(), TaskOrigin::User);

        let new_tasks = vec![
            BrainTask { id: 10, name: "x".into(), origin: TaskOrigin::User, result: None },
            BrainTask { id: 11, name: "y".into(), origin: TaskOrigin::User, result: None },
        ];
        q.replace(new_tasks);

        assert_eq!(q.len(), 2);
        assert_eq!(q.pop_front().unwrap().name, "x");
    }

    #[test]
    fn parse_task_list_numbered() {
        let response = "1. Fix the compiler error\n2. Run tests\n3. Update docs\n";
        let tasks = parse_task_list(response);
        assert_eq!(tasks, vec!["Fix the compiler error", "Run tests", "Update docs"]);
    }

    #[test]
    fn parse_task_list_no_new_tasks() {
        let response = "No new tasks.";
        let tasks = parse_task_list(response);
        assert!(tasks.is_empty());
    }

    #[test]
    fn parse_task_list_ignores_non_numbered() {
        let response = "Here are some tasks:\n1. First\nNot a task\n2. Second\n";
        let tasks = parse_task_list(response);
        assert_eq!(tasks, vec!["First", "Second"]);
    }

    #[test]
    fn goal_pursuit_lifecycle() {
        let mut gp = GoalPursuit::new();
        assert!(!gp.is_active());

        gp.set_objective("fix all bugs".into(), "run cargo test".into());
        assert!(gp.is_active());
        assert!(!gp.should_stop());

        let task = gp.queue.pop_front().unwrap();
        assert_eq!(task.name, "run cargo test");

        gp.record_completion(task, TaskResult {
            data: "3 tests failed".into(),
            success: false,
            timestamp_secs: 0,
        });

        assert_eq!(gp.current_cycle, 1);
        assert!(gp.queue.is_empty()); // No new tasks yet
    }

    #[test]
    fn reflexion_memory_sliding_window() {
        let mut mem = ReflexionMemory::new("sig".into(), "fix bug".into());
        mem.add_reflection("tried A, failed".into());
        mem.add_reflection("tried B, failed".into());
        mem.add_reflection("tried C, failed".into());
        mem.add_reflection("tried D, failed".into());

        // Should only keep last 3.
        assert_eq!(mem.reflections.len(), 3);
        assert!(mem.reflections[0].text.contains("B"));
        assert!(mem.reflections[1].text.contains("C"));
        assert!(mem.reflections[2].text.contains("D"));
    }

    #[test]
    fn reflexion_inject_into_prompt() {
        let mut mem = ReflexionMemory::new("sig".into(), "fix bug".into());
        mem.add_reflection("Don't forget to run tests".into());

        let prompt = inject_reflections("Base prompt.", "Fix the bug", &mem);
        assert!(prompt.contains("Base prompt."));
        assert!(prompt.contains("Lessons from past attempts"));
        assert!(prompt.contains("Don't forget to run tests"));
        assert!(prompt.contains("Fix the bug"));
    }

    #[test]
    fn reflection_prompt_includes_trajectory() {
        let prompt = build_reflection_prompt(
            "> cargo test\n3 failures\n",
            &["tried fixing imports"],
        );
        assert!(prompt.contains("cargo test"));
        assert!(prompt.contains("3 failures"));
        assert!(prompt.contains("tried fixing imports"));
    }

    #[test]
    fn goal_pursuit_summary() {
        let mut gp = GoalPursuit::new();
        gp.set_objective("ship v1".into(), "build".into());
        let s = gp.summary();
        assert!(s.contains("ship v1"));
        assert!(s.contains("0 done"));
        assert!(s.contains("1 remaining"));
    }
}
